### ISSUE TITLE
incorrect cipher_list

### ISSUE THREAD

**Issue by cochoiate** [aarond10/powermeter_hub_server#2]
I am running the hub_server.py on a raspberry pi B (Raspbian GNU/Linux 10 (buster) )
After execute the python hub_server.py I am receiving this error:
```
**python hub_server.py**
_Traceback (most recent call last):
  File "hub_server.py", line 145, in <module>
    run_server()
  File "hub_server.py", line 136, in run_server
    httpd = SecureHTTPServer(server_address, FakeEfergyServer)
  File "hub_server.py", line 16, in __init__
    ctx.set_cipher_list('RC4-MD5')
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1186, in set_cipher_list
    _lib.SSL_CTX_set_cipher_list(self._context, cipher_list) == 1
  File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 67, in openssl_assert
    exception_from_error_queue(error)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'SSL_CTX_set_cipher_list', 'no cipher match')]_
```
I have tryied to modify the line:    ctx.set_cipher_list('RC4-MD5')
But I am not sure what is the correct cipher that I have to use

the command openssl ciphers -v  dumps a lot of different cipher but the one used on the code is missing

`openssl ciphers -v
TLS_AES_256_GCM_SHA384  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(256) Mac=AEAD
TLS_CHACHA20_POLY1305_SHA256 TLSv1.3 Kx=any      Au=any  Enc=CHACHA20/POLY1305(256) Mac=AEAD
TLS_AES_128_GCM_SHA256  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(128) Mac=AEAD
ECDHE-ECDSA-AES256-GCM-SHA384 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AESGCM(256) Mac=AEAD
ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AESGCM(256) Mac=AEAD
DHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=DH       Au=RSA  Enc=AESGCM(256) Mac=AEAD
ECDHE-ECDSA-CHACHA20-POLY1305 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=CHACHA20/POLY1305(256) Mac=AEAD
ECDHE-RSA-CHACHA20-POLY1305 TLSv1.2 Kx=ECDH     Au=RSA  Enc=CHACHA20/POLY1305(256) Mac=AEAD
DHE-RSA-CHACHA20-POLY1305 TLSv1.2 Kx=DH       Au=RSA  Enc=CHACHA20/POLY1305(256) Mac=AEAD
ECDHE-ECDSA-AES128-GCM-SHA256 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AESGCM(128) Mac=AEAD
ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AESGCM(128) Mac=AEAD
DHE-RSA-AES128-GCM-SHA256 TLSv1.2 Kx=DH       Au=RSA  Enc=AESGCM(128) Mac=AEAD
ECDHE-ECDSA-AES256-SHA384 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AES(256)  Mac=SHA384
ECDHE-RSA-AES256-SHA384 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AES(256)  Mac=SHA384
DHE-RSA-AES256-SHA256   TLSv1.2 Kx=DH       Au=RSA  Enc=AES(256)  Mac=SHA256
ECDHE-ECDSA-AES128-SHA256 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=AES(128)  Mac=SHA256
ECDHE-RSA-AES128-SHA256 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AES(128)  Mac=SHA256
DHE-RSA-AES128-SHA256   TLSv1.2 Kx=DH       Au=RSA  Enc=AES(128)  Mac=SHA256
ECDHE-ECDSA-AES256-SHA  TLSv1 Kx=ECDH     Au=ECDSA Enc=AES(256)  Mac=SHA1
ECDHE-RSA-AES256-SHA    TLSv1 Kx=ECDH     Au=RSA  Enc=AES(256)  Mac=SHA1
DHE-RSA-AES256-SHA      SSLv3 Kx=DH       Au=RSA  Enc=AES(256)  Mac=SHA1
ECDHE-ECDSA-AES128-SHA  TLSv1 Kx=ECDH     Au=ECDSA Enc=AES(128)  Mac=SHA1
ECDHE-RSA-AES128-SHA    TLSv1 Kx=ECDH     Au=RSA  Enc=AES(128)  Mac=SHA1
DHE-RSA-AES128-SHA      SSLv3 Kx=DH       Au=RSA  Enc=AES(128)  Mac=SHA1
RSA-PSK-AES256-GCM-SHA384 TLSv1.2 Kx=RSAPSK   Au=RSA  Enc=AESGCM(256) Mac=AEAD
DHE-PSK-AES256-GCM-SHA384 TLSv1.2 Kx=DHEPSK   Au=PSK  Enc=AESGCM(256) Mac=AEAD
RSA-PSK-CHACHA20-POLY1305 TLSv1.2 Kx=RSAPSK   Au=RSA  Enc=CHACHA20/POLY1305(256) Mac=AEAD
DHE-PSK-CHACHA20-POLY1305 TLSv1.2 Kx=DHEPSK   Au=PSK  Enc=CHACHA20/POLY1305(256) Mac=AEAD
ECDHE-PSK-CHACHA20-POLY1305 TLSv1.2 Kx=ECDHEPSK Au=PSK  Enc=CHACHA20/POLY1305(256) Mac=AEAD
AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
PSK-AES256-GCM-SHA384   TLSv1.2 Kx=PSK      Au=PSK  Enc=AESGCM(256) Mac=AEAD
PSK-CHACHA20-POLY1305   TLSv1.2 Kx=PSK      Au=PSK  Enc=CHACHA20/POLY1305(256) Mac=AEAD
RSA-PSK-AES128-GCM-SHA256 TLSv1.2 Kx=RSAPSK   Au=RSA  Enc=AESGCM(128) Mac=AEAD
DHE-PSK-AES128-GCM-SHA256 TLSv1.2 Kx=DHEPSK   Au=PSK  Enc=AESGCM(128) Mac=AEAD
AES128-GCM-SHA256       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(128) Mac=AEAD
PSK-AES128-GCM-SHA256   TLSv1.2 Kx=PSK      Au=PSK  Enc=AESGCM(128) Mac=AEAD
AES256-SHA256           TLSv1.2 Kx=RSA      Au=RSA  Enc=AES(256)  Mac=SHA256
AES128-SHA256           TLSv1.2 Kx=RSA      Au=RSA  Enc=AES(128)  Mac=SHA256
ECDHE-PSK-AES256-CBC-SHA384 TLSv1 Kx=ECDHEPSK Au=PSK  Enc=AES(256)  Mac=SHA384
ECDHE-PSK-AES256-CBC-SHA TLSv1 Kx=ECDHEPSK Au=PSK  Enc=AES(256)  Mac=SHA1
SRP-RSA-AES-256-CBC-SHA SSLv3 Kx=SRP      Au=RSA  Enc=AES(256)  Mac=SHA1
SRP-AES-256-CBC-SHA     SSLv3 Kx=SRP      Au=SRP  Enc=AES(256)  Mac=SHA1
RSA-PSK-AES256-CBC-SHA384 TLSv1 Kx=RSAPSK   Au=RSA  Enc=AES(256)  Mac=SHA384
DHE-PSK-AES256-CBC-SHA384 TLSv1 Kx=DHEPSK   Au=PSK  Enc=AES(256)  Mac=SHA384
RSA-PSK-AES256-CBC-SHA  SSLv3 Kx=RSAPSK   Au=RSA  Enc=AES(256)  Mac=SHA1
DHE-PSK-AES256-CBC-SHA  SSLv3 Kx=DHEPSK   Au=PSK  Enc=AES(256)  Mac=SHA1
AES256-SHA              SSLv3 Kx=RSA      Au=RSA  Enc=AES(256)  Mac=SHA1
PSK-AES256-CBC-SHA384   TLSv1 Kx=PSK      Au=PSK  Enc=AES(256)  Mac=SHA384
PSK-AES256-CBC-SHA      SSLv3 Kx=PSK      Au=PSK  Enc=AES(256)  Mac=SHA1
ECDHE-PSK-AES128-CBC-SHA256 TLSv1 Kx=ECDHEPSK Au=PSK  Enc=AES(128)  Mac=SHA256
ECDHE-PSK-AES128-CBC-SHA TLSv1 Kx=ECDHEPSK Au=PSK  Enc=AES(128)  Mac=SHA1
SRP-RSA-AES-128-CBC-SHA SSLv3 Kx=SRP      Au=RSA  Enc=AES(128)  Mac=SHA1
SRP-AES-128-CBC-SHA     SSLv3 Kx=SRP      Au=SRP  Enc=AES(128)  Mac=SHA1
RSA-PSK-AES128-CBC-SHA256 TLSv1 Kx=RSAPSK   Au=RSA  Enc=AES(128)  Mac=SHA256
DHE-PSK-AES128-CBC-SHA256 TLSv1 Kx=DHEPSK   Au=PSK  Enc=AES(128)  Mac=SHA256
RSA-PSK-AES128-CBC-SHA  SSLv3 Kx=RSAPSK   Au=RSA  Enc=AES(128)  Mac=SHA1
DHE-PSK-AES128-CBC-SHA  SSLv3 Kx=DHEPSK   Au=PSK  Enc=AES(128)  Mac=SHA1
AES128-SHA              SSLv3 Kx=RSA      Au=RSA  Enc=AES(128)  Mac=SHA1
PSK-AES128-CBC-SHA256   TLSv1 Kx=PSK      Au=PSK  Enc=AES(128)  Mac=SHA256
PSK-AES128-CBC-SHA      SSLv3 Kx=PSK      Au=PSK  Enc=AES(128)  Mac=SHA1
`

I also tried to regenerate the cert file without success.
This is the cert.pem included with the software:

 ```
openssl x509 -in cert.pem -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            9d:dd:9a:1a:c0:ee:7c:46
        Signature Algorithm: sha1WithRSAEncryption
        Issuer: O = sensornet, emailAddress = ops@hildebrand.co.uk, L = London, ST = London, C = GB, CN = *.sensornet.info
        Validity
            Not Before: Jan 18 12:42:46 2015 GMT
            Not After : Jan 15 12:42:46 2025 GMT
        Subject: O = sensornet, emailAddress = ops@hildebrand.co.uk, L = London, ST = London, C = GB, CN = *.sensornet.info
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (1024 bit)
                Modulus:
                    00:ba:9a:14:bb:87:7f:c4:aa:e3:13:54:c6:08:e6:
                    45:83:e5:05:45:5d:6b:53:91:c6:25:d4:bd:8e:41:
                    3d:3a:ec:76:4e:0c:17:d9:14:a0:74:4b:a0:d0:b6:
                    78:e7:36:a3:fb:2f:b0:bf:1e:b4:ad:18:fc:b1:b2:
                    70:fb:a9:d9:b2:1b:ff:11:40:78:e2:08:dd:67:b1:
                    2f:09:4f:f1:9b:7a:03:bf:99:06:2d:a0:5f:c5:3e:
                    36:0a:bf:7c:9f:9a:9d:9a:e7:25:4d:37:5d:a2:21:
                    e5:59:4c:fd:cc:48:fa:5f:dc:20:6e:34:f3:7c:ed:
                    33:f1:d8:ce:f7:68:fc:a0:a1
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints:
                CA:TRUE
            X509v3 Subject Key Identifier:
                42:89:18:93:6C:0A:6D:AB:79:42:4F:85:11:A1:5D:43:0F:9F:DA:DA
            X509v3 Authority Key Identifier:
                keyid:42:89:18:93:6C:0A:6D:AB:79:42:4F:85:11:A1:5D:43:0F:9F:DA:DA
                DirName:/O=sensornet/emailAddress=ops@hildebrand.co.uk/L=London/ST=London/C=GB/CN=*.sensornet.info
                serial:9D:DD:9A:1A:C0:EE:7C:46

    Signature Algorithm: sha1WithRSAEncryption
         93:ce:a3:77:1b:45:b0:8c:18:bb:b5:58:2a:92:4a:b1:e5:7a:
         97:96:6b:fe:af:cd:ce:b7:0b:30:19:8a:c5:ea:43:cb:85:3b:
         d5:ab:16:a5:63:e2:ec:93:50:f8:97:3b:41:9a:39:9a:3f:96:
         85:e9:24:49:5d:55:78:b5:76:d2:d1:ad:f9:4c:42:52:c2:94:
         9f:1b:11:b4:d4:b3:32:db:fc:bb:70:d3:79:7e:01:d7:a4:4d:
         62:4a:d9:53:21:d8:a1:21:cb:89:ad:fc:89:78:f6:94:b0:8d:
         6c:6d:30:85:fa:fe:a6:9a:bf:36:7d:1d:66:36:29:40:86:74:
         61:9c
-----BEGIN CERTIFICATE-----
MIIDcjCCAtugAwIBAgIJAJ3dmhrA7nxGMA0GCSqGSIb3DQEBBQUAMIGDMRIwEAYD
VQQKEwlzZW5zb3JuZXQxIzAhBgkqhkiG9w0BCQEWFG9wc0BoaWxkZWJyYW5kLmNv
LnVrMQ8wDQYDVQQHEwZMb25kb24xDzANBgNVBAgTBkxvbmRvbjELMAkGA1UEBhMC
R0IxGTAXBgNVBAMUECouc2Vuc29ybmV0LmluZm8wHhcNMTUwMTE4MTI0MjQ2WhcN
MjUwMTE1MTI0MjQ2WjCBgzESMBAGA1UEChMJc2Vuc29ybmV0MSMwIQYJKoZIhvcN
AQkBFhRvcHNAaGlsZGVicmFuZC5jby51azEPMA0GA1UEBxMGTG9uZG9uMQ8wDQYD
VQQIEwZMb25kb24xCzAJBgNVBAYTAkdCMRkwFwYDVQQDFBAqLnNlbnNvcm5ldC5p
bmZvMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC6mhS7h3/EquMTVMYI5kWD
5QVFXWtTkcYl1L2OQT067HZODBfZFKB0S6DQtnjnNqP7L7C/HrStGPyxsnD7qdmy
G/8RQHjiCN1nsS8JT/GbegO/mQYtoF/FPjYKv3yfmp2a5yVNN12iIeVZTP3MSPpf
3CBuNPN87TPx2M73aPygoQIDAQABo4HrMIHoMAwGA1UdEwQFMAMBAf8wHQYDVR0O
BBYEFEKJGJNsCm2reUJPhRGhXUMPn9raMIG4BgNVHSMEgbAwga2AFEKJGJNsCm2r
eUJPhRGhXUMPn9raoYGJpIGGMIGDMRIwEAYDVQQKEwlzZW5zb3JuZXQxIzAhBgkq
hkiG9w0BCQEWFG9wc0BoaWxkZWJyYW5kLmNvLnVrMQ8wDQYDVQQHEwZMb25kb24x
DzANBgNVBAgTBkxvbmRvbjELMAkGA1UEBhMCR0IxGTAXBgNVBAMUECouc2Vuc29y
bmV0LmluZm+CCQCd3ZoawO58RjANBgkqhkiG9w0BAQUFAAOBgQCTzqN3G0WwjBi7
tVgqkkqx5XqXlmv+r83OtwswGYrF6kPLhTvVqxalY+Lsk1D4lztBmjmaP5aF6SRJ
XVV4tXbS0a35TEJSwpSfGxG01LMy2/y7cNN5fgHXpE1iStlTIdihIcuJrfyJePaU
sI1sbTCF+v6mmr82fR1mNilAhnRhnA==
-----END CERTIFICATE-----

```

Thank you so much for the support!!

**Comment by aarond10** [comment]
Ah, this code is many years old. I don't have a device at hand but I
RC4-MD5 is not considered secure these days and I imagine it has probably
been removed from your ssl library. I don't have another device on hand to
test but you might have luck removing that line and trying again. If the
device requires that cipher, you'll need to get an older copy of SSL to
build against.
