### ISSUE TITLE
Inconsistent use of tabs

### ISSUE THREAD

**Issue by jckruger** [aarond10/powermeter_hub_server#3]
My efergy account has been pooched and I can't get support to help me with is so have decided to go around them and stumbled upon this project.

I'm having some difficulty getting it going though. I have just cloned the project to my rpie and have run as you have said

```
python ./web_server.py 
  File "/etc/powermeter_hub_server/./web_server.py", line 26
    path = 'static/%s' % url.path[len(self.STATIC):]
TabError: inconsistent use of tabs and spaces in indentation
```

```
python ./hub_server.py 
  File "/etc/powermeter_hub_server/./hub_server.py", line 58
    content = "TT|a1bCDEFGHa1zZ\n"
TabError: inconsistent use of tabs and spaces in indentation
```

I have even tried fixing the indents with an online beautifier (https://www.tutorialspoint.com/online_python_formatter.htm) and it still shows errors.

This looks promising but I'm not a python guru some help would be great

**Comment by jckruger** [comment]
if I use the beautifier on the hub_server.py then I get

```
python ./hub_server.py 
  File "/etc/powermeter_hub_server/./hub_server.py", line 92
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

**Comment by aarond10** [comment]
I haven't used this in years, but I think you might be using python3. The code was likely written in python2. If that is the only error, you might get away with changing it to `except Exception as e`, but there may be other issues. Can you try running with python2?

**Comment by jckruger** [comment]
I’ll give it a try. Not sure how to run in v2 but I’ll figure it out.

**Comment by jckruger** [comment]
Very hard to get a working copy of Python2 working as it has been removed for a while. Tried updating the code to work with v3 and still having issues.

I might try seeing if I can point my hub to a apache box with the self-signed cert and log any headers an outputs. I just tried packet capturing from my firewall and I can't see much except for the sslv3 cert and handshakes. I'll give it a try and if not I might bin it.

Great code though to do what it did.

**Comment by aarond10** [comment]
Yeah, I think mine is in a box somewhere but I don't remember where. I
can't make any promises but if I find it I might try to update the code a
bit.

It shouldn't be too hard if you know python but may be a stretch if you
don't. (If you're feeling brave, you might even be able to ask an AI to
update it for you these days. :D)

I hate the idea of throwing out perfectly good hardware because the
manufacturer has abandoned it.

**Comment by jckruger** [comment]
Ha Ha, Yes I did get chatGPT to try and also a python2 to python3 converter [https://python2to3.com/](url) which came up with the same code. There were a few things converted. I also had to properly indent some lines content =  I think was the line.

Now it complains about libssl.so. Seems there are a lot of dependencies now.

Code now looks like this
```
import db
from socketserver import BaseServer
from http.server import HTTPServer
from http.server import SimpleHTTPRequestHandler
from OpenSSL import SSL
import logging
import time
import socket
import urllib.parse

class SecureHTTPServer(HTTPServer):
  def __init__(self, server_address, HandlerClass):
    BaseServer.__init__(self, server_address, HandlerClass)
    ctx = SSL.Context(SSL.SSLv23_METHOD)
    fpem = 'cert.pem'
    ctx.set_cipher_list('RC4-MD5')
    ctx.use_privatekey_file(fpem)
    ctx.use_certificate_file(fpem)
    self.socket = SSL.Connection(ctx, socket.socket(self.address_family,
                                                    self.socket_type))
    self.server_bind()
    self.server_activate()

  def shutdown_request(self, request):
    """We will shut down ourselves."""
    pass

class SecureHTTPRequestHandler(SimpleHTTPRequestHandler):
  def setup(self):
    self.connection = self.request
    self.rfile = socket._fileobject(self.request, "rb", self.rbufsize)
    self.wfile = socket._fileobject(self.request, "wb", self.wbufsize)

class FakeEfergyServer(SecureHTTPRequestHandler):
  """Pretends to be a sensornet.info server.

  The firmware in the hub that I have (v1.1 AU) *requires* HTTP/1.1 and 
  a graceful SSL shutdown handshake. SSL certificate fields may also be 
  checked but I've just copied all of those so I'm not sure.
  """
  protocol_version = 'HTTP/1.1'

  def do_GET(self):
    try:
      url = urllib.parse.urlparse(self.path)
      q = urllib.parse.parse_qs(url.query)

      code = 200
      content = ""
      if url.path == '/get_key.html':
        content = "TT|a1bCDEFGHa1zZ\n"
      elif url.path == '/check_key.html':
        content = "\n"

      self.send_response(code)
      self.send_header("Content-Type", "text/html; charset=UTF-8")
      self.send_header("Content-Length", len(content))
      self.end_headers()
      self.wfile.write(content)
      logging.error('GET: %s', (url, dict(self.headers)))
    except Exception as e:
      logging.error("Exception: %s", e)
    
    # Shutdown SSL before closing the connection. 
    self.close_connection = 1
    self.connection.shutdown()
    self.connection.close()

  def do_POST(self):
    url = urllib.parse.urlparse(self.path)
    q = urllib.parse.parse_qs(url.query)

    if url.path == '/h2' or url.path == '/h3':
      # Sensor data!
      # Headers look like this:
      #   x-uptime: <seconds since boot>
      #   x-hash: <unknown hash algorithm. 64-bit>
      #   x-version: 2.3.7
      #   x-pair: P
      #   x-mode: E1
      #   x-ts: <uptime seconds as 32-bit hex value>:<milliseconds in decimal?>
      #   content-type: application/eh-data
      # This is followed by a \r\n-terminated line for each connected sensor.
      # Data for each sensor looks like this:
      #   <SID>|1|<SensorType>|<Port>,<value to 2 decimal places>
      #   SID is a sensor id, a 6 digit integer. I've seen this be zero occasionally,
      #   which typically goes away after we respond with a 200 OK.
      #   SensorType is EFCT for CT transmitters, not sure about others - but I've seen my EFT
      #   sensor return 'EFMS1' in this field:
      #     <SID>|0|EFMS1|M,64.00&T,0.00&L,0.00|-62
      #   Port is P1, even on (my) multi-CT setup.
    
      hubVersion = url.path.strip('/')
      httpData = self.rfile.read(int(self.headers['content-length']))
      sensorLines = httpData.split('\r\n')
      for line in sensorLines:
            if len(line) == 0:
              continue
            data = line.split('|')
            SID = data[0]
            if SID == '0':
                continue
            portAndValue = data[3]
            value = float(portAndValue.split(',')[1])
            label = 'efergy_%s_%s' % (hubVersion, SID)
            logging.info("%s, %s, %s, %s" % (SID, url.path, time.time(), value))
            db.LogData(label, value)
      
    self.send_response(200)
    self.send_header("Content-Type", "text/html; charset=UTF-8")
    self.end_headers()

    # Shutdown SSL before closing the connection. 
    self.close_connection = 1
    self.connection.shutdown()
    self.connection.close()

def run_server():
  server_address = ('', 8080) # (address, port)
  httpd = SecureHTTPServer(server_address, FakeEfergyServer)
  sa = httpd.socket.getsockname()
  print("Serving HTTPS on", sa[0], "port", sa[1], "...")
  httpd.serve_forever()


if __name__ == '__main__':
  logging.basicConfig()
  db.SetupDb('readings.db')
  run_server()
```
and errors like this

python ./hub_server.py 
Traceback (most recent call last):
  File "/etc/powermeter_hub_server/./hub_server.py", line 5, in <module>
    from OpenSSL import SSL
  File "/usr/local/lib/python3.9/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/usr/local/lib/python3.9/dist-packages/OpenSSL/SSL.py", line 11, in <module>
    from OpenSSL._util import (
  File "/usr/local/lib/python3.9/dist-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/local/lib/python3.9/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 15, in <module>
    from cryptography.exceptions import InternalError
  File "/usr/local/lib/python3.9/dist-packages/cryptography/exceptions.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: libssl.so.3: cannot open shared object file: No such file or directory

I did read a few articles about symlinking directories or trying to install some other packages but I had no luck. Maybe I'll try with a clean machine with Centos or something.

I'd be interested to know how you managed to packet capture the hub

**Comment by jckruger** [comment]
I think I have something nearly working for python3 (I’ll share if it looks promising) but I need to test some post data at it with jmeter. If I have the syntax correct does the post look like this:

000000|0|EFMS1|M,64.00&T,0.00&L,0.00|-62\r\n

what are the fields? I’m using your example for the above.

I have never used python before but your code and lots of googling have helped.

I’ve also commented the connection.shutdown and close for now as I have them in a different place.

I’ll see if I can also get the we server code working so I can see what is logged to the database. Maybe I should just try pointing my hub to it.

**Comment by aarond10** [comment]
Seems like you've got something going! Great!

The fields are above in the comment block. The EFMS1 I think might be the
hub itself. I dont know what the values mean but if you sync your ct
clamps, you should see them too.
